// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: sensitive_manager.proto

package sensitive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,20,opt,name=password,proto3" json:"password,omitempty"`
	DisplayName   string                 `protobuf:"bytes,30,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_sensitive_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_sensitive_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,20,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_sensitive_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken      string                 `protobuf:"bytes,20,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Salt             []byte                 `protobuf:"bytes,30,opt,name=salt,proto3" json:"salt,omitempty"`
	EncryptedDataKey []byte                 `protobuf:"bytes,40,opt,name=encrypted_data_key,json=encryptedDataKey,proto3" json:"encrypted_data_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_sensitive_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{3}
}

func (x *LoginUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginUserResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginUserResponse) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *LoginUserResponse) GetEncryptedDataKey() []byte {
	if x != nil {
		return x.EncryptedDataKey
	}
	return nil
}

type AddCredentialDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,10,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Login         string                 `protobuf:"bytes,20,opt,name=login,proto3" json:"login,omitempty"`
	Password      []byte                 `protobuf:"bytes,30,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCredentialDataRequest) Reset() {
	*x = AddCredentialDataRequest{}
	mi := &file_sensitive_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialDataRequest) ProtoMessage() {}

func (x *AddCredentialDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialDataRequest.ProtoReflect.Descriptor instead.
func (*AddCredentialDataRequest) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{4}
}

func (x *AddCredentialDataRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AddCredentialDataRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AddCredentialDataRequest) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type AddCredentialDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretDataId  int64                  `protobuf:"varint,10,opt,name=secret_data_id,json=secretDataId,proto3" json:"secret_data_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCredentialDataResponse) Reset() {
	*x = AddCredentialDataResponse{}
	mi := &file_sensitive_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialDataResponse) ProtoMessage() {}

func (x *AddCredentialDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialDataResponse.ProtoReflect.Descriptor instead.
func (*AddCredentialDataResponse) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{5}
}

func (x *AddCredentialDataResponse) GetSecretDataId() int64 {
	if x != nil {
		return x.SecretDataId
	}
	return 0
}

type GetCredentialDataListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialDataListRequest) Reset() {
	*x = GetCredentialDataListRequest{}
	mi := &file_sensitive_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialDataListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialDataListRequest) ProtoMessage() {}

func (x *GetCredentialDataListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialDataListRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialDataListRequest) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{6}
}

type CredentialData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,10,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Login         string                 `protobuf:"bytes,20,opt,name=login,proto3" json:"login,omitempty"`
	Password      []byte                 `protobuf:"bytes,30,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialData) Reset() {
	*x = CredentialData{}
	mi := &file_sensitive_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialData) ProtoMessage() {}

func (x *CredentialData) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialData.ProtoReflect.Descriptor instead.
func (*CredentialData) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{7}
}

func (x *CredentialData) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CredentialData) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CredentialData) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type GetCredentialDataListResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CredentialData []*CredentialData      `protobuf:"bytes,10,rep,name=credential_data,json=credentialData,proto3" json:"credential_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCredentialDataListResponse) Reset() {
	*x = GetCredentialDataListResponse{}
	mi := &file_sensitive_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialDataListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialDataListResponse) ProtoMessage() {}

func (x *GetCredentialDataListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialDataListResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialDataListResponse) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{8}
}

func (x *GetCredentialDataListResponse) GetCredentialData() []*CredentialData {
	if x != nil {
		return x.CredentialData
	}
	return nil
}

type AddTextDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,10,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,20,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTextDataRequest) Reset() {
	*x = AddTextDataRequest{}
	mi := &file_sensitive_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTextDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTextDataRequest) ProtoMessage() {}

func (x *AddTextDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTextDataRequest.ProtoReflect.Descriptor instead.
func (*AddTextDataRequest) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{9}
}

func (x *AddTextDataRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AddTextDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddTextDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretDataId  int64                  `protobuf:"varint,10,opt,name=secret_data_id,json=secretDataId,proto3" json:"secret_data_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTextDataResponse) Reset() {
	*x = AddTextDataResponse{}
	mi := &file_sensitive_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTextDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTextDataResponse) ProtoMessage() {}

func (x *AddTextDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTextDataResponse.ProtoReflect.Descriptor instead.
func (*AddTextDataResponse) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{10}
}

func (x *AddTextDataResponse) GetSecretDataId() int64 {
	if x != nil {
		return x.SecretDataId
	}
	return 0
}

type GetTextDataListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextDataListRequest) Reset() {
	*x = GetTextDataListRequest{}
	mi := &file_sensitive_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextDataListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextDataListRequest) ProtoMessage() {}

func (x *GetTextDataListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextDataListRequest.ProtoReflect.Descriptor instead.
func (*GetTextDataListRequest) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{11}
}

type NoteData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,10,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,20,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteData) Reset() {
	*x = NoteData{}
	mi := &file_sensitive_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteData) ProtoMessage() {}

func (x *NoteData) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteData.ProtoReflect.Descriptor instead.
func (*NoteData) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{12}
}

func (x *NoteData) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *NoteData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTextDataListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteData      []*NoteData            `protobuf:"bytes,10,rep,name=note_data,json=noteData,proto3" json:"note_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextDataListResponse) Reset() {
	*x = GetTextDataListResponse{}
	mi := &file_sensitive_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextDataListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextDataListResponse) ProtoMessage() {}

func (x *GetTextDataListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextDataListResponse.ProtoReflect.Descriptor instead.
func (*GetTextDataListResponse) Descriptor() ([]byte, []int) {
	return file_sensitive_manager_proto_rawDescGZIP(), []int{13}
}

func (x *GetTextDataListResponse) GetNoteData() []*NoteData {
	if x != nil {
		return x.NoteData
	}
	return nil
}

var File_sensitive_manager_proto protoreflect.FileDescriptor

const file_sensitive_manager_proto_rawDesc = "" +
	"\n" +
	"\x17sensitive_manager.proto\x12\x13sensitivemanager.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"j\n" +
	"\x13RegisterUserRequest\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x14 \x01(\tR\bpassword\x12!\n" +
	"\fdisplay_name\x18\x1e \x01(\tR\vdisplayName\"/\n" +
	"\x14RegisterUserResponse\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\x03R\x06userId\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x14 \x01(\tR\bpassword\"\x91\x01\n" +
	"\x11LoginUserResponse\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\x03R\x06userId\x12!\n" +
	"\faccess_token\x18\x14 \x01(\tR\vaccessToken\x12\x12\n" +
	"\x04salt\x18\x1e \x01(\fR\x04salt\x12,\n" +
	"\x12encrypted_data_key\x18( \x01(\fR\x10encryptedDataKey\"o\n" +
	"\x18AddCredentialDataRequest\x12!\n" +
	"\fservice_name\x18\n" +
	" \x01(\tR\vserviceName\x12\x14\n" +
	"\x05login\x18\x14 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x1e \x01(\fR\bpassword\"A\n" +
	"\x19AddCredentialDataResponse\x12$\n" +
	"\x0esecret_data_id\x18\n" +
	" \x01(\x03R\fsecretDataId\"\x1e\n" +
	"\x1cGetCredentialDataListRequest\"e\n" +
	"\x0eCredentialData\x12!\n" +
	"\fservice_name\x18\n" +
	" \x01(\tR\vserviceName\x12\x14\n" +
	"\x05login\x18\x14 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x1e \x01(\fR\bpassword\"m\n" +
	"\x1dGetCredentialDataListResponse\x12L\n" +
	"\x0fcredential_data\x18\n" +
	" \x03(\v2#.sensitivemanager.v1.CredentialDataR\x0ecredentialData\"K\n" +
	"\x12AddTextDataRequest\x12!\n" +
	"\fservice_name\x18\n" +
	" \x01(\tR\vserviceName\x12\x12\n" +
	"\x04data\x18\x14 \x01(\fR\x04data\";\n" +
	"\x13AddTextDataResponse\x12$\n" +
	"\x0esecret_data_id\x18\n" +
	" \x01(\x03R\fsecretDataId\"\x18\n" +
	"\x16GetTextDataListRequest\"A\n" +
	"\bNoteData\x12!\n" +
	"\fservice_name\x18\n" +
	" \x01(\tR\vserviceName\x12\x12\n" +
	"\x04data\x18\x14 \x01(\fR\x04data\"U\n" +
	"\x17GetTextDataListResponse\x12:\n" +
	"\tnote_data\x18\n" +
	" \x03(\v2\x1d.sensitivemanager.v1.NoteDataR\bnoteData2\x9b\x05\n" +
	"\x14SensitiveDataService\x12c\n" +
	"\fRegisterUser\x12(.sensitivemanager.v1.RegisterUserRequest\x1a).sensitivemanager.v1.RegisterUserResponse\x12Z\n" +
	"\tLoginUser\x12%.sensitivemanager.v1.LoginUserRequest\x1a&.sensitivemanager.v1.LoginUserResponse\x12r\n" +
	"\x11AddCredentialData\x12-.sensitivemanager.v1.AddCredentialDataRequest\x1a..sensitivemanager.v1.AddCredentialDataResponse\x12~\n" +
	"\x15GetCredentialDataList\x121.sensitivemanager.v1.GetCredentialDataListRequest\x1a2.sensitivemanager.v1.GetCredentialDataListResponse\x12`\n" +
	"\vAddTextData\x12'.sensitivemanager.v1.AddTextDataRequest\x1a(.sensitivemanager.v1.AddTextDataResponse\x12l\n" +
	"\x0fGetTextDataList\x12+.sensitivemanager.v1.GetTextDataListRequest\x1a,.sensitivemanager.v1.GetTextDataListResponseBCZAgithub.com/ruslanDantsov/password_manager/pkg/sensitive;sensitiveb\x06proto3"

var (
	file_sensitive_manager_proto_rawDescOnce sync.Once
	file_sensitive_manager_proto_rawDescData []byte
)

func file_sensitive_manager_proto_rawDescGZIP() []byte {
	file_sensitive_manager_proto_rawDescOnce.Do(func() {
		file_sensitive_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sensitive_manager_proto_rawDesc), len(file_sensitive_manager_proto_rawDesc)))
	})
	return file_sensitive_manager_proto_rawDescData
}

var file_sensitive_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sensitive_manager_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),           // 0: sensitivemanager.v1.RegisterUserRequest
	(*RegisterUserResponse)(nil),          // 1: sensitivemanager.v1.RegisterUserResponse
	(*LoginUserRequest)(nil),              // 2: sensitivemanager.v1.LoginUserRequest
	(*LoginUserResponse)(nil),             // 3: sensitivemanager.v1.LoginUserResponse
	(*AddCredentialDataRequest)(nil),      // 4: sensitivemanager.v1.AddCredentialDataRequest
	(*AddCredentialDataResponse)(nil),     // 5: sensitivemanager.v1.AddCredentialDataResponse
	(*GetCredentialDataListRequest)(nil),  // 6: sensitivemanager.v1.GetCredentialDataListRequest
	(*CredentialData)(nil),                // 7: sensitivemanager.v1.CredentialData
	(*GetCredentialDataListResponse)(nil), // 8: sensitivemanager.v1.GetCredentialDataListResponse
	(*AddTextDataRequest)(nil),            // 9: sensitivemanager.v1.AddTextDataRequest
	(*AddTextDataResponse)(nil),           // 10: sensitivemanager.v1.AddTextDataResponse
	(*GetTextDataListRequest)(nil),        // 11: sensitivemanager.v1.GetTextDataListRequest
	(*NoteData)(nil),                      // 12: sensitivemanager.v1.NoteData
	(*GetTextDataListResponse)(nil),       // 13: sensitivemanager.v1.GetTextDataListResponse
}
var file_sensitive_manager_proto_depIdxs = []int32{
	7,  // 0: sensitivemanager.v1.GetCredentialDataListResponse.credential_data:type_name -> sensitivemanager.v1.CredentialData
	12, // 1: sensitivemanager.v1.GetTextDataListResponse.note_data:type_name -> sensitivemanager.v1.NoteData
	0,  // 2: sensitivemanager.v1.SensitiveDataService.RegisterUser:input_type -> sensitivemanager.v1.RegisterUserRequest
	2,  // 3: sensitivemanager.v1.SensitiveDataService.LoginUser:input_type -> sensitivemanager.v1.LoginUserRequest
	4,  // 4: sensitivemanager.v1.SensitiveDataService.AddCredentialData:input_type -> sensitivemanager.v1.AddCredentialDataRequest
	6,  // 5: sensitivemanager.v1.SensitiveDataService.GetCredentialDataList:input_type -> sensitivemanager.v1.GetCredentialDataListRequest
	9,  // 6: sensitivemanager.v1.SensitiveDataService.AddTextData:input_type -> sensitivemanager.v1.AddTextDataRequest
	11, // 7: sensitivemanager.v1.SensitiveDataService.GetTextDataList:input_type -> sensitivemanager.v1.GetTextDataListRequest
	1,  // 8: sensitivemanager.v1.SensitiveDataService.RegisterUser:output_type -> sensitivemanager.v1.RegisterUserResponse
	3,  // 9: sensitivemanager.v1.SensitiveDataService.LoginUser:output_type -> sensitivemanager.v1.LoginUserResponse
	5,  // 10: sensitivemanager.v1.SensitiveDataService.AddCredentialData:output_type -> sensitivemanager.v1.AddCredentialDataResponse
	8,  // 11: sensitivemanager.v1.SensitiveDataService.GetCredentialDataList:output_type -> sensitivemanager.v1.GetCredentialDataListResponse
	10, // 12: sensitivemanager.v1.SensitiveDataService.AddTextData:output_type -> sensitivemanager.v1.AddTextDataResponse
	13, // 13: sensitivemanager.v1.SensitiveDataService.GetTextDataList:output_type -> sensitivemanager.v1.GetTextDataListResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_sensitive_manager_proto_init() }
func file_sensitive_manager_proto_init() {
	if File_sensitive_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sensitive_manager_proto_rawDesc), len(file_sensitive_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sensitive_manager_proto_goTypes,
		DependencyIndexes: file_sensitive_manager_proto_depIdxs,
		MessageInfos:      file_sensitive_manager_proto_msgTypes,
	}.Build()
	File_sensitive_manager_proto = out.File
	file_sensitive_manager_proto_goTypes = nil
	file_sensitive_manager_proto_depIdxs = nil
}
