// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO users (
    id,
    email,
    password_hash,
    display_name
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreatePaymentParams struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	DisplayName  *string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.Exec(ctx, createPayment,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
	)
	return err
}
